#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.0f1_b6ffa8986c8d"
#define UNITY_VERSION_FULL_NICE "2018.4.0f1 (b6ffa8986c8d)"
#define UNITY_VERSION_BLD 11993000
#define UNITY_VERSION_DATE 1556658355
#define UNITY_VERSION_WIN "2018.4.0.11993000"
#define UNITY_VERSION_BRANCH "2018.4/staging"
